"""
Hindsight Memory Manager for Proposal Builder
Manages persistent memory of proposals, refinements, and user preferences
"""

import json
from typing import Dict, Any, List, Optional
from datetime import datetime
from hindsight import Hindsight, MemoryBank

# Initialize Hindsight client
# For hackathon: assumes local Hindsight server running on default port
hindsight_client = None


def initialize_hindsight(api_key: str = None, base_url: str = "http://localhost:8090") -> Hindsight:
    """
    Initialize Hindsight client
    For hackathon deployment, uses local server by default
    """
    global hindsight_client
    try:
        if api_key:
            hindsight_client = Hindsight(api_key=api_key, base_url=base_url)
        else:
            # Local deployment - no API key required
            hindsight_client = Hindsight(base_url=base_url)
        print("✅ Hindsight initialized successfully")
        return hindsight_client
    except Exception as e:
        print(f"⚠️  Hindsight initialization failed: {e}")
        print("💡 Make sure Hindsight server is running locally or provide API credentials")
        hindsight_client = None
        return None


class HindsightManager:
    """Manage Hindsight memory operations for proposal builder"""
    
    MEMORY_BANK_NAME = "proposal_builder"
    MISSION = """
    I am a Proposal Builder AI Assistant. My purpose is to generate professional, 
    compelling business proposals that are customized to each client's needs. 
    I retain knowledge about proposal structures, content patterns, user preferences,
    and past successful proposals to improve future generations.
    I prefer clarity, professionalism, and client-specific customization.
    """
    
    DIRECTIVES = [
        "Always cite or reference relevant past proposal patterns when available",
        "Never generate generic or one-size-fits-all content - personalize based on discovered preferences",
        "Maintain consistency across proposal sections",
        "Preserve user refinement choices as strong signals for future proposals"
    ]
    
    def __init__(self, client: Optional[Hindsight] = None):
        """Initialize with Hindsight client"""
        self.client = client or hindsight_client
        self.memory_bank = None
        
        if self.client:
            self._setup_memory_bank()
    
    def _setup_memory_bank(self):
        """Create or get the memory bank for proposal builder"""
        try:
            # Get or create memory bank
            self.memory_bank = self.client.memory_bank(
                name=self.MEMORY_BANK_NAME,
                mission=self.MISSION,
                directives=self.DIRECTIVES,
                disposition={
                    "professionalism": 5,
                    "creativity": 4,
                    "thoroughness": 5,
                    "empathy": 3
                }
            )
            print(f"✅ Memory bank '{self.MEMORY_BANK_NAME}' ready")
        except Exception as e:
            print(f"⚠️  Error setting up memory bank: {e}")
    
    def retain_proposal(self, proposal_data: Dict[str, Any]) -> bool:
        """
        Retain a generated proposal in memory
        
        Args:
            proposal_data: Dict containing:
                - discovery_data: extracted from discovery document
                - generated_content: content generated by Gemini
                - proposal_id: unique proposal identifier
                - created_at: timestamp
        """
        if not self.client or not self.memory_bank:
            return False
        
        try:
            proposal_id = proposal_data.get("proposal_id", "unknown")
            discovery_data = proposal_data.get("discovery_data", {})
            generated_content = proposal_data.get("generated_content", {})
            
            # Create a summary of the proposal
            summary = self._create_proposal_summary(discovery_data, generated_content)
            
            # Retain the proposal in Hindsight
            self.memory_bank.retain(
                content=summary,
                source=f"proposal_{proposal_id}",
                metadata={
                    "type": "proposal",
                    "proposal_id": proposal_id,
                    "industry": discovery_data.get("industry", "unknown"),
                    "client": discovery_data.get("client_name", "unknown"),
                    "created_at": proposal_data.get("created_at", datetime.now().isoformat())
                }
            )
            print(f"✅ Retained proposal {proposal_id} in Hindsight")
            return True
        except Exception as e:
            print(f"⚠️  Error retaining proposal: {e}")
            return False
    
    def retain_refinements(self, proposal_id: str, refinements: str, original_content: Dict[str, Any]) -> bool:
        """
        Retain user refinements as feedback for future proposals
        
        Args:
            proposal_id: ID of the proposal being refined
            refinements: User's requested changes
            original_content: Original generated content
        """
        if not self.client or not self.memory_bank:
            return False
        
        try:
            feedback_summary = f"""
User Refinement Feedback for Proposal {proposal_id}:
Requested Changes: {refinements}

This indicates user preferences and areas for improvement in future proposals.
User preferred modifications suggest their style preferences and requirements.
            """
            
            self.memory_bank.retain(
                content=feedback_summary,
                source=f"refinement_{proposal_id}",
                metadata={
                    "type": "user_feedback",
                    "proposal_id": proposal_id,
                    "refinement_count": 1,
                    "feedback_timestamp": datetime.now().isoformat()
                }
            )
            print(f"✅ Retained refinement feedback for proposal {proposal_id}")
            return True
        except Exception as e:
            print(f"⚠️  Error retaining refinements: {e}")
            return False
    
    def recall_similar_proposals(self, discovery_data: Dict[str, Any], limit: int = 3) -> List[Dict[str, Any]]:
        """
        Recall similar past proposals to inform current generation
        
        Args:
            discovery_data: Current discovery document data
            limit: Max number of similar proposals to return
        
        Returns:
            List of similar proposal memories with context
        """
        if not self.client or not self.memory_bank:
            return []
        
        try:
            # Build a query from discovery data
            query = self._build_recall_query(discovery_data)
            
            # Recall from memory bank using multi-strategy search
            memories = self.memory_bank.recall(
                query=query,
                limit=limit,
                strategies=["semantic", "keyword", "temporal"]  # Use multiple search strategies
            )
            
            if memories:
                print(f"✅ Recalled {len(memories)} similar proposals from memory")
                return [mem for mem in memories]
            return []
        except Exception as e:
            print(f"⚠️  Error recalling proposals: {e}")
            return []
    
    def recall_user_preferences(self, limit: int = 5) -> List[Dict[str, Any]]:
        """
        Recall user preferences from past refinements
        
        Returns:
            List of user preference patterns
        """
        if not self.client or not self.memory_bank:
            return []
        
        try:
            query = "user preferences refinement style feedback changes"
            
            memories = self.memory_bank.recall(
                query=query,
                limit=limit,
                strategies=["semantic", "keyword"]
            )
            
            if memories:
                print(f"✅ Recalled {len(memories)} user preference patterns")
                return [mem for mem in memories]
            return []
        except Exception as e:
            print(f"⚠️  Error recalling preferences: {e}")
            return []
    
    def reflect_for_generation(self, discovery_data: Dict[str, Any]) -> str:
        """
        Use Hindsight's reflect() to consolidate knowledge and get contextual guidance
        for proposal generation
        
        Args:
            discovery_data: Current proposal's discovery data
        
        Returns:
            Consolidated context/guidance for Gemini prompt
        """
        if not self.client or not self.memory_bank:
            return ""
        
        try:
            query = f"""
            Based on my memory of past proposals:
            - For industry: {discovery_data.get('industry', 'unknown')}
            - For clients similar to: {discovery_data.get('client_name', 'unknown')}
            - What patterns, structures, and content approaches worked well?
            - What did users prefer to change or refine?
            - How should I approach this proposal given the user's history?
            """
            
            # Reflect consolidates observations and applies reasoning
            reflections = self.memory_bank.reflect(query=query)
            
            if reflections:
                print(f"✅ Generated reflections for proposal generation")
                return reflections
            return ""
        except Exception as e:
            print(f"⚠️  Error in reflect: {e}")
            return ""
    
    def _create_proposal_summary(self, discovery_data: Dict[str, Any], generated_content: Dict[str, Any]) -> str:
        """Create a text summary of a proposal for memory storage"""
        summary = f"""
Proposal Summary:
- Client: {discovery_data.get('client_name', 'Unknown')}
- Industry: {discovery_data.get('industry', 'Unknown')}
- Scope: {discovery_data.get('project_scope', 'Unspecified')}

Content Generated:
"""
        # Include high-level content structure
        if isinstance(generated_content, dict):
            for slide_num, content in generated_content.items():
                if isinstance(content, dict):
                    summary += f"\n- Slide {slide_num}: {list(content.keys())}"
        
        return summary
    
    def _build_recall_query(self, discovery_data: Dict[str, Any]) -> str:
        """Build a search query from discovery data"""
        industry = discovery_data.get("industry", "")
        client_type = discovery_data.get("client_type", "")
        scope = discovery_data.get("project_scope", "")
        
        query = f"{industry} {client_type} {scope} proposal template content"
        return query.strip()
    
    def get_status(self) -> Dict[str, Any]:
        """Get current status of Hindsight integration"""
        return {
            "connected": self.client is not None,
            "memory_bank_ready": self.memory_bank is not None,
            "bank_name": self.MEMORY_BANK_NAME if self.memory_bank else None
        }


# Singleton instance
_manager = None


def get_hindsight_manager() -> HindsightManager:
    """Get or initialize the global Hindsight manager"""
    global _manager
    if _manager is None:
        client = initialize_hindsight()
        _manager = HindsightManager(client)
    return _manager
